# basic options
title: Indus Blog
author: IndusWell
email: induswell@domain.com
description: A Blog for the Ages
twitter_username: induswell
github_username: induswell

# Build settings
markdown: kramdown
theme: minima
